version: "3.9"

networks:
  demo-cloud-net:
    driver: bridge

services:
  consul-server:
    image: consul
    ports:
      - "8500:8500"
    networks:
      - demo-cloud-net
  api-gateway:
    build: ./ApiGatewayV1
    ports:
      - "8080:8080"
    networks:
      - demo-cloud-net
    depends_on:
      - consul-server
  api-gateway-2:
    build: ./ApiGatewayV2
    ports:
      - "8080:8080"
    networks:
      - demo-cloud-net
    depends_on:
      - consul-server
  film-service:
#    container_name: FilmService
    deploy:
      replicas: 3
    build: ./FilmService
#    ports:
#      - "8080:8080"
    networks:
      - demo-cloud-net
    depends_on:
      - consul-server
  client-service:
    container_name: ClientService
    build: ./ClientService
    ports:
      - "8181:8181"
    networks:
      - demo-cloud-net
    depends_on:
      - consul-server
