spring:
  application:
    name: Gateway2

  cloud:
    consul:
      host: localhost
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.uuid}

    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: to-client
          uri: lb://client-service
          predicates:
            - Path=/client/**
            - Method=GET,POST
          filters:
            - name: Logger
            - RewritePath=/client/(?<path>.*),/$\{path}
            - AddRequestParameter=mon-param,sa-valeur
            - Retry=3
        - id: to-film
          uri: lb://film-service
          predicates:
            - Path=/film/**
          filters:
            - RewritePath=/film/(?<path>.*),/$\{path}
        - id: mot
          uri: lb://film-service
          predicates:
            - Path=/mot
            - name: NumberOfParams
              args:
                equals: 0
#                min: 0
#                max: 0
          filters:
#            - name: Secured
            - name: AddRequestParameter
              args:
                name: mot
                value: gateway
            - name: Logger
        - id: login
          uri: lb://user-service
          predicates:
            - Path=/login
            - Method=POST
          filters:
            - name: Logger


