spring:
  profiles:
    active: dev
  application:
    name: film-service

  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.uuid}
#        health-check-path: "/actuator/health"

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
          - mappings
          - metrics
